name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "Sadanand Pai"
          git config user.email "sadypai@gmail.com"

      # Runs a set of commands using the runners shell
      - name: setup deployment
        run: |
          npm install
          npm test
          npm run e2e:test
          rm -rf dist
          npm run build
          git add dist -f
          git diff --staged --quiet || (git commit -m "build files - github action" && git push)
